server:
  port: 8080

spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/MvcMovieApp"
    username: "postgres"
    password: "23061995"
    driver-class-name: "org.postgresql.Driver"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

